package sbnz.integracija;

import com.example.SBNZApp.facts.*;


declare SuspiciousCustomerEvent
    @role(event)
    customerId: Long
    reason: String
end

global SmestajAlarm smestajAlarm;

rule "Vise od 5 poseta smestaju u 10 minuta i salje se obavestenje korisniku"
    agenda-group "cep"
	when
	        $t1: PutovanjeEvent($cId: user.ID)
	        Number(intValue >= 5) from accumulate(
	            $t2: PutovanjeEvent(
	                this != $t1, 
	                user.ID == $cId
	            )over window:time(10m),
	            count($t2)
	        )
	        not (SuspiciousCustomerEvent(customerId == $cId, reason == "Puno rezervisanih smestaja"))
	    then
	     
	        insert(new SuspiciousCustomerEvent($cId, "Puno rezervisanih smestaja"));
	        smestajAlarm.setUserId($cId);
end

rule "Jedan SuspiciousCustomerEvent u danu i salje se obavestenje administratoru"
    agenda-group "cep"
    when
        SuspiciousCustomerEvent($cId: customerId)
        Number(intValue >= 0) from accumulate(
            $s: SuspiciousCustomerEvent(customerId == $cId),
            count($s)
        )
    then
        insert(new AlarmTriggered($cId));
end

